name: functional_enum_annotation
description: Annotations for the functional_enum code generator package.
version: 1.2.0
homepage: https://github.com/Elias8/functional_enum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

