name: example
description: A sample command-line application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  functional_enum_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.2
  test: ^1.17.12
  functional_enum:
    path: ../
