name: example
description: A sample command-line application.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  functional_enum_annotation: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.1
  test: ^1.15.3
  functional_enum:
    path: ../
