name: example
description: A sample command-line application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  functional_enum_annotation: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.1
  test: ^1.21.6
  functional_enum:
    path: ../
