builders:
  functional_enum:
    target: ":functional_enum"
    import: "package:functional_enum/builder.dart"
    builder_factories: ["functionalEnum"]
    build_extensions: { ".dart": [".enum.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]

