name: functional_enum
description: Code generator for functional enum that makes the use of enums much better.
version: 1.0.1
homepage: https://github.com/Elias8/functional_enum

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: '>=0.39.5 <0.40.0'
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  functional_enum_annotation: ^1.0.0
  meta: ^1.2.3
  source_gen: ^0.9.6