name: functional_enum
description: Code generator for functional enum that makes the use of enums much better.
version: 1.1.7
homepage: https://github.com/Elias8/functional_enum

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  build: ^2.3.1
  build_config: ^1.1.0
  functional_enum_annotation:
    git:
      url: https://github.com/AdamBuchweitz/functional_enum.git
      path: packages/functional_enum_annotation
  source_gen: ^1.2.5
